//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SourceParameters_.h
//  Source: /home/rameez/ADAS_ROS2/ADAS_ws/src/ADASPackage/rosidl_generator_dds_idl/adas_pipeline/msg/dds_opensplice/SourceParameters_.idl
//  Generated: Thu Mar 24 10:52:16 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _SOURCEPARAMETERS__H_
#define _SOURCEPARAMETERS__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace adas_pipeline
{
   namespace msg
   {
      namespace dds_
      {
         struct SourceParameters_;

         struct SourceParameters_
         {
               DDS::Long inputmode_;
               DDS::Long device_;
               DDS::String_mgr dir_;
               DDS::Float fps_;
               DDS::Boolean paused_;
         };

         typedef DDS_DCPSStruct_var < SourceParameters_> SourceParameters__var;
         typedef DDS_DCPSStruct_out < SourceParameters_> SourceParameters__out;
      }
   }
}




#endif 
