//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SourceParameters_Dcps.cpp
//  Source: /home/rameez/ADAS_ROS2/ADAS_ws/src/ADASPackage/rosidl_typesupport_opensplice_cpp/adas_pipeline/msg/dds_opensplice/SourceParameters_Dcps.idl
//  Generated: Thu Mar 24 10:52:16 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "SourceParameters_Dcps.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < adas_pipeline::msg::dds_::SourceParameters_, struct SourceParameters_Seq_uniq_>;
#endif

const char * adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface::_local_id = "IDL:adas_pipeline/msg/dds_/SourceParameters_TypeSupportInterface:1.0";

adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface::_duplicate (adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface::_local_is_a (const char * _id)
{
   if (strcmp (_id, adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::TypeSupport NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface::_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr result = NULL;
   if (p && p->_is_a (adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface::_local_id))
   {
      result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface::_unchecked_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr result;
   result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_TypeSupportInterface_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * adas_pipeline::msg::dds_::SourceParameters_DataWriter::_local_id = "IDL:adas_pipeline/msg/dds_/SourceParameters_DataWriter:1.0";

adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr adas_pipeline::msg::dds_::SourceParameters_DataWriter::_duplicate (adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean adas_pipeline::msg::dds_::SourceParameters_DataWriter::_local_is_a (const char * _id)
{
   if (strcmp (_id, adas_pipeline::msg::dds_::SourceParameters_DataWriter::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataWriter NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr adas_pipeline::msg::dds_::SourceParameters_DataWriter::_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr result = NULL;
   if (p && p->_is_a (adas_pipeline::msg::dds_::SourceParameters_DataWriter::_local_id))
   {
      result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr adas_pipeline::msg::dds_::SourceParameters_DataWriter::_unchecked_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr result;
   result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_DataWriter_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * adas_pipeline::msg::dds_::SourceParameters_DataReader::_local_id = "IDL:adas_pipeline/msg/dds_/SourceParameters_DataReader:1.0";

adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr adas_pipeline::msg::dds_::SourceParameters_DataReader::_duplicate (adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean adas_pipeline::msg::dds_::SourceParameters_DataReader::_local_is_a (const char * _id)
{
   if (strcmp (_id, adas_pipeline::msg::dds_::SourceParameters_DataReader::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReader NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr adas_pipeline::msg::dds_::SourceParameters_DataReader::_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr result = NULL;
   if (p && p->_is_a (adas_pipeline::msg::dds_::SourceParameters_DataReader::_local_id))
   {
      result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr adas_pipeline::msg::dds_::SourceParameters_DataReader::_unchecked_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr result;
   result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_DataReader_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * adas_pipeline::msg::dds_::SourceParameters_DataReaderView::_local_id = "IDL:adas_pipeline/msg/dds_/SourceParameters_DataReaderView:1.0";

adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr adas_pipeline::msg::dds_::SourceParameters_DataReaderView::_duplicate (adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean adas_pipeline::msg::dds_::SourceParameters_DataReaderView::_local_is_a (const char * _id)
{
   if (strcmp (_id, adas_pipeline::msg::dds_::SourceParameters_DataReaderView::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReaderView NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr adas_pipeline::msg::dds_::SourceParameters_DataReaderView::_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr result = NULL;
   if (p && p->_is_a (adas_pipeline::msg::dds_::SourceParameters_DataReaderView::_local_id))
   {
      result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr adas_pipeline::msg::dds_::SourceParameters_DataReaderView::_unchecked_narrow (DDS::Object_ptr p)
{
   adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr result;
   result = dynamic_cast < adas_pipeline::msg::dds_::SourceParameters_DataReaderView_ptr> (p);
   if (result) result->m_count++;
   return result;
}



