// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.template

#ifndef ADAS_PIPELINE__MSG__SOURCE_PARAMETERS__INTROSPECTION__TYPE_SUPPORT_H_
#define ADAS_PIPELINE__MSG__SOURCE_PARAMETERS__INTROSPECTION__TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#include "adas_pipeline/msg/rosidl_generator_c__visibility_control.h"

static rosidl_message_type_support_t adas_pipeline__msg__rosidl_typesupport_introspection_c__SourceParameters_message_type_support_handle;

#if __cplusplus
extern "C"
{
#endif

ROSIDL_GENERATOR_C_PUBLIC_adas_pipeline
const rosidl_message_type_support_t *
rosidl_get_message_type_support__adas_pipeline__msg__SourceParameters();

#if __cplusplus
}
#endif

#endif  // ADAS_PIPELINE__MSG__SOURCE_PARAMETERS__INTROSPECTION__TYPE_SUPPORT_H_
